baseURL = "http://example.org/"
languageCode = "en-us"
title = "CN"
theme = "beautifulhugo"


[Params]
  homeTitle = "Centralized Notes" # Set a different text for the header on the home page
  subtitle = "Learning about zk-SNARKS"
  mainSections = ["post","posts"]
  logo = "img/zk-logo.png" # Expecting square dimensions
  favicon = "img/zk-logo.png"
  dateFormat = "January 2, 2006"
  commit = false
  rss = false
  comments = false
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
  hideAuthor = true
